version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rozklad_reverse_proxy
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      - NODE_ENV=prod
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: rozklad_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
